services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: warehouse
    ports:
      - "5432:5432"

  examples.warehouse.inbound:
    image: examples.warehouse.inbound
    build:
      context: .
      dockerfile: examples.warehouse.inbound.Dockerfile
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SERVER_PORT=8081
    ports:
      - '8081:8081'

  examples.warehouse.order:
    image: examples.warehouse.order
    build:
      context: .
      dockerfile: examples.warehouse.order.Dockerfile
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SERVER_PORT=8080
    ports:
      - '8080:8080'

  examples.warehouse.stocktake:
    image: examples.warehouse.stocktake
    build:
      context: .
      dockerfile: examples.warehouse.stocktake.Dockerfile
    environment:
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/warehouse
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - SERVER_PORT=8082
    ports:
      - '8082:8082'


  examples.warehouse.inventory:
    image: examples.warehouse.inventory
    build:
      context: .
      dockerfile: examples.warehouse.inventory.Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/warehouse
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres

  examples.warehouse.shipping:
    image: examples.warehouse.shipping
    build:
      context: .
      dockerfile: examples.warehouse.shipping.Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
